---
name: snapcast-server-libspot
version: dev
slug: snapcast-server-libspot
description: Host a Snapcast server with librespot
url: https://github.com/rwjack/addon-snapserver-spotify
codenotary: jack@foss.family
arch:
  - aarch64
  - amd64
  - armv7
  - i386
map: ["share:rw"]
audio: true
init: false
options:
  server:
    threads: "-1"
    datadir: "/data/snapserver"
  spotify:
    credentials: ""
    device_name: "HA_Snapcast"
    cache_dir: "/data/librespot"
    cache_size_limit: "2G"
    bitrate: 320
    volume: 100
    bypass_apresolve: false
  stream:
    streams: "tcp://0.0.0.0:4953?name=TTS&codec=pcm&mode=server"
    buffer: 1000
    codec: "flac"
    send_to_muted: true
    sampleformat: "48000:16:2"
  http:
    enabled: true
    bind_to_address: "0.0.0.0"
  tcp:
    enabled: true
  logging:
    enabled: false
schema:
  server:
    datadir: str
    threads: int?
  spotify:
    credentials: str
    device_name: str
    cache_dir: str
    cache_size_limit: str
    bitrate: list(96|160|320)
    volume: int(0,100)
    bypass_apresolve: bool
  stream:
    streams: str?
    bis: str?
    ter: str?
    buffer: int?
    codec: str?
    send_to_muted: bool?
    sampleformat: str?
  http:
    enabled: bool?
    bind_to_address: str?
    doc_root: str?
  tcp:
    enabled: bool?
  logging:
    enabled: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
ports:
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
  4953/tcp: 4953
ports_description:
  1704/tcp: Snapcast Stream
  1705/tcp: Snapcast JSON RPC
  1780/tcp: Snapcast HTTP controller
  4953/tcp: Snapcast HA TTS listener
